#-----------------------------------------------------------------------

baseurl = "http://leg.ufpr.br/~walmes/leg-site/"
title = "LEG"
theme = "hugo-universal-theme"
themesDir = "./themes/"
languageCode = "pt-br"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
ignoreFiles = ["\\.R$", "\\.Rmd$", "\\.sh", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

#-----------------------------------------------------------------------
# Main menu.

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Ensino"
    identifier = "main_ensino"
    weight = 2

[[menu.main]]
    parent = "main_ensino"
    name = "Disciplinas"
    url  = "/disciplinas/"
    weight = 1

[[menu.main]]
    parent = "main_ensino"
    name = "Cursos"
    url  = "/cursos/"
    weight = 2

[[menu.main]]
    parent = "main_ensino"
    name = "Conferências"
    url  = "/conferencias/"
    weight = 3

[[menu.main]]
    parent = "main_ensino"
    name = "Videos"
    url  = "/videos/"
    weight = 4

[[menu.main]]
    name = "Projetos"
    identifier = "main_projetos"
    weight = 3

[[menu.main]]
    parent = "main_projetos"
    name = "Projetos"
    url  = "/projetos/"
    weight = 1

[[menu.main]]
    parent = "main_projetos"
    name = "Cooperações"
    url  = "/cooperacoes/"
    weight = 2

[[menu.main]]
    name = "Pessoas"
    url  = "/pessoas/"
    weight = 4

[[menu.main]]
    name = "Publicações"
    # identifier = "publications"
    url  = "/publicacoes/"
    weight = 4

[[menu.main]]
    name = "Agenda"
    url  = "/agenda/"
    weight = 5

# [[menu.main]]
#     name = "Contato"
#     url  = "/contato/"
#     weight = 6

# [[menu.main]]
#     name = "Blog"
#     url  = "/blog/"
#     weight = 6

#-----------------------------------------------------------------------
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Email"
    url = "mailto:leg.ufpr@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/leg-ufpr"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/LEG_UFPR"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Facebook"
    url = "http://facebook.com/leg.ufpr"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

#-----------------------------------------------------------------------
[params]
    viewMorePostLink = "/blog/"
    author = "Walmes Zeviani"
    defaultKeywords = ["RStats", "GnuEmacs", "Linux"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "orange"

    custom_css = ["./css/custom.css"]

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "leg.ufpr@gmail.com"

    about_us = """<p>Geoinformation and Statistics Laboratory<br>Department of Statistics<br>Federal University of Paraná, Brazil.</p>
        <img src='http://www.ufpr.br/portalufpr/wp-content/themes/wpufpr_zurb6_portalufpr/images/logo_ufpr_branca.png' width='240px'/>"""
    copyright = "Copyright (c) 2018; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # logo = "img/logo.png"
    logo = "img/logo-leg-topo.png"
    logo_small = "img/ufpr-topo.png"
    address = """<p>
        <strong>Laboratório de Estatística e Geoinformação</strong>
        <br>Edifício do Setor de Ciências Exatas - 2º andar - sala 232
        <br>Campus III - Centro Politécnico - UFPR
        <br>+55 41 3361 3573 | +55 41 3361 3141<br>
        <br>Rua Evaristo F. F. da Costa, 393
        <br>Jardim das Americas, Curitiba, PR
        <br>Caixa Postal 19.081
        <br>CEP 81.531-980
      </p>
      """
    latitude = "-25.4502711"
    longitude = "-49.2328839"

#-----------------------------------------------------------------------

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

#-----------------------------------------------------------------------
# Enable or disable top bar with social icons

[params.topbar]
    enable = true
    text = ""
    # text = """<p class="hidden-sm hidden-xs">Contact me on +55 41 3361 3573 or walmes@ufpr.br.</p>
    #   <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
    #   <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    #   </p>
    #   """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

# [params.carousel]
#     enable = true
#     # All carousel items are defined in their own files. You can find example items
#     # at 'exampleSite/data/carousel'.
#     # For more informtion take a look at the README.

# [params.features]
#     enable = true
#     # All features are defined in their own files. You can find example items
#     # at 'exampleSite/data/features'.
#     # For more informtion take a look at the README.

# [params.testimonials]
#     enable = true
#     # All testimonials are defined in their own files. You can find example items
#     # at 'exampleSite/data/testimonials'.
#     # For more informtion take a look at the README.
#     title = "Testimonials"
#     subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

# [params.see_more]
#     enable = true
#     icon = "fa fa-file-code-o"
#     title = "Do you want to see more?"
#     subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
#     link_url = "#"
#     link_text = "Check other homepages"

# [params.clients]
#     enable = true
#     # All clients are defined in their own files. You can find example items
#     # at 'exampleSite/data/clients'.
#     # For more informtion take a look at the README.
#     # title = "Our Clients"
#     # subtitle = ""

# [params.recent_posts]
#     enable = false
#     title = "From my blog"
#     subtitle = "Some posts abou Statistics, R, GNU Emacs, Linux. Enjoy!"

#-----------------------------------------------------------------------
